version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitconnect-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: nodemon --legacy-watch index.js
    environment:
      - NODE_ENV=development
    restart: always
